name: ffi_just_to_workaround_stuff
version: 0.1.3
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/ffi
description: Utilities for working with Foreign Function Interface (FFI) code.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
